version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: jieshixin
      POSTGRES_PASSWORD: jieshixin,.#
      POSTGRES_DB: ticflow
    ports:
      - 28432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 31080:8080

  app:
    image: enhydrawgc/sddm-backend
    restart: unless-stopped
    ports:
      - 21081:8080

  ui:
    image: nginx:1.21.1-alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/var/www
    restart: unless-stopped
    ports:
      - 21080:80