version: '3.1'

services:

  db:
    image: enhydrawgc/sddm-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: jieshixin
      POSTGRES_PASSWORD: jieshixin,.#
      POSTGRES_DB: ticflow
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 31080:8080

  sddm-backend:
    image: enhydrawgc/sddm-backend
    restart: unless-stopped
    ports:
      - 21081:8080

  sddm-web:
    image: enhydrawgc/sddm-frontend
    restart: unless-stopped
    ports:
      - 21080:80