@startuml online

' 为记录公司赚多少钱
class 毛利

class 现金

class 预存{
    销售人员
    客户名称
    到账时间
    发票号
}

预存 "1" -- "1" 发票

class 发票 {
    发票号
    金额
    开票公司
    开票时间
    销售人员
    到账时间
    是否回款结束
}


class 回款 {
    发票号
    时间
    金额
}

发票 "1" -- "*" 回款

class 支出{
    金额
    时间
    备注
    是否现金
}

class 客户支出

支出 <|- 客户支出
支出 <|- 公司支出



class 收入{
    金额
    日期
}

收入 <|- 毛利
收入 <|- 现金
收入 <|- 预存

预存 "1" -- "*" 客户支出

class 人员
class 销售人员

人员 <|- 销售人员

class 销售支出{
    销售人员
    编号
}



毛利 "1"--"1" 销售人员
毛利 "1"--"*" 销售支出


' 为记录公司花多少钱

class 行政管理费


公司支出 <|- 行政管理费
公司支出 <|- 销售支出
公司支出 <|- 现金工资

class 公司支出 {
    类型（包括总经办支持）    
}

class 保证金{
    人员
    收回时间
    用途
    是否已平
}

公司支出 <|- 保证金


@enduml