@startuml "train"

class 项目 {
    项目名称
    项目编号
    项目简介
    项目负责人
    项目状态
    计划开始时间
    计划结束时间
}
class 列车 {
    列车编号
}

class 车箱 {
    车箱类型
    车箱编号
}

class 模块 {
    模块名称
    模块编号
    父模块名称
    父模块编号
    检修流程
}

class 零部件 {
    零部件名称
    原有零部件编号
    更换后零部件编号
}

'class 流程 {
'    流程id
'}

class 组装记录 {
    组装时间
    组装记录
}

class 检修记录 {
    检修模块名称
    检修工具编号
    检修记录
}

class 工序指导书 {
    工序名称
    工序编号
    施工标准
    作业方法
}

class 计量器具 {
    器具编号
    器具名称
    器具型号
    生产厂家
    设备分类
    使用部门
    备注
}

class 使用记录 {
    设备名称
    设备编号
    操作人
    操作时间
}

class 来料登记表 {
    初检记录
    司机姓名
    车牌号
    登记人
    登记时间
}

class 工单 {
    工单编号
    工期
    问题描述
    问题类型
    问题原因
    问题提出人
    问题提出时间
    处理人
    处理时间
    处理结果 
}

Abstract Class 检修条目

列车 "1" -* "1" 工单
项目 "1" --* "n" 列车
来料登记表 "1" -* "1" 列车
列车 "1" --* "n" 车箱
组装记录 "1" -* "n" 车箱
车箱 "1" --* "n" 模块
检修记录 "1" - "1" 模块
模块 "1" --* "n" 零部件
检修过程 "1" - "1" 零部件
检修记录 "1" --* "n" 检修过程
计量器具 o-- 检修条目
使用记录  "1" - "1" 计量器具
'工序指导书 "1" - "1" 模块
'流程 "1" - "1" 车箱
模块 "1" - "n" 模块
检修条目 *- 检修过程
工序指导书 "1" - "1" 检修条目
检修条目 <|-- 清洁
检修条目 <|-- 更换
检修条目 <|-- 维修保养
检修条目 <|-- 检测
'检修条目 <|-- 实验

'项目 "1" o-- "n" 列车
'车厢 "n" <--* "1" 列车
'模块 "n" <--* "1" 车厢
'工序指导书 ..> 模块
'组装记录 ..> 车厢
'检修记录 ..> 模块
'检修记录 ..> 使用记录
'检修记录 ..> 零部件
'模块 o-- 零部件
'流程 ..> 模块

'计量设备 ..> 检修记录
'来料 o-- 列车
'工单 ..> 列车
'使用记录 ..> 计量设备

@enduml