@startuml online

class 支出{
    金额
    时间
    备注
    是否现金
}

class 公司支出 {
    类型（包括总经办支持）    
}

支出 <|- 公司支出

class 保证金{
    人员
    收回时间
    用途
    是否已平
}

公司支出 <|- 保证金

class 现金工资

公司支出 <|- 现金工资

class 行政管理费

公司支出 <|- 行政管理费

class 客户支出

支出 <|- 客户支出

class 销售支出{
    销售人员
    编号
}

公司支出 <|- 销售支出

@enduml