version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: jieshixin
      POSTGRES_PASSWORD: jieshixin,.#
      POSTGRES_DB: ticflow
    ports:
      - 28432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 31080:8080